# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 853302a0449ebd22e5481062a6d813aa392bb72c034ce7782fae68504e46aeb16bb6eeb3eb432ed6da49946e8621982d3ff6b8906230ebf113609db5a55cea85

test:
  secret_key_base: 8cf64d2970e76c79b7c78350e41dc4e5adcd264fb25c6255bd9da755ce5386dfac0696d1a2af96907a0971c1ec483ed9792a3361c71db0f50197561779ce53fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
